// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtz9E4H3e1hpv9mkjI2yujIthJzTP1Lk',
    appId: '1:1035260170011:web:23579d5e7866187d310dbe',
    messagingSenderId: '1035260170011',
    projectId: 'universo-de-noah',
    authDomain: 'universo-de-noah.firebaseapp.com',
    storageBucket: 'universo-de-noah.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbzEe5HdlVgskK8KjswMxKizfH5bGkMg',
    appId: '1:1035260170011:ios:21c7f35fe7d7f66b310dbe',
    messagingSenderId: '1035260170011',
    projectId: 'universo-de-noah',
    storageBucket: 'universo-de-noah.firebasestorage.app',
    iosBundleId: 'com.example.universoDeNoah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtz9E4H3e1hpv9mkjI2yujIthJzTP1Lk',
    appId: '1:1035260170011:web:37f157074358089d310dbe',
    messagingSenderId: '1035260170011',
    projectId: 'universo-de-noah',
    authDomain: 'universo-de-noah.firebaseapp.com',
    storageBucket: 'universo-de-noah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KLCdGYNbRv16QGkygRkXKdom4n8uX2I',
    appId: '1:1035260170011:android:b710ccd582a8dfa9310dbe',
    messagingSenderId: '1035260170011',
    projectId: 'universo-de-noah',
    storageBucket: 'universo-de-noah.firebasestorage.app',
  );

}